### ISSUE TITLE
"nvme discover" gives unnecessary error if there is no device present for discovery

### ISSUE THREAD

**Issue by pareshpp** [linux-nvme/nvme-cli#253] opened 2018-01-09 07:09 UTC
If there is no existing device for nvme to discover, it gives error as shown below. 

# nvme discover -t rdma -s 1032 -a 192.168.10.11
Failed to write to /dev/nvme-fabrics: Connection reset by peer
#

This error is misleading to the user. There need not be any error as such if there are no devices found in discovery. There could be user readable message like no existing devices found or empty string.

**Comment by keithbusch** [comment] 2018-01-09 16:41
I think the tool is just reporting an error passed up from the kernel. I don't think it necessarily knows the reason for the error can be ignored.

**Comment by hreinecke** [comment] 2022-01-16 10:09
Agreed. Closing as it works as designed.

**Closed by hreinecke** 2022-01-16 10:09 UTC
