### ISSUE TITLE
Trying to format a locked ssd using nvme-cli gives INVALID_OPCODE error

### ISSUE THREAD

**Issue by deepakagrawal** [linux-nvme/nvme-cli#779] opened 2020-07-18 05:38 UTC
Hi I have a Samsung 970 EVO plus which I locked from bios. I tried recovering the data and I couldn't so I am just formatting the drive so that I can use it again. I am using the `nvme format` command to format the drive. But it gives me the following error.

```
    root@deepak-GL502VM:/home/deepak# nvme format /dev/nvme0 -n 1
    NVMe status: INVALID_OPCODE: The associated command opcode field is not valid(0x1)

```

Any help would be greatly appreciated.

**Comment by keithbusch** [comment] 2020-07-18 18:54
Is this a duplicate of https://github.com/linux-nvme/nvme-cli/issues/627
?

**Comment by Flameancer** [comment] 2020-08-21 04:59
It looks like this is still an issue. `Systemctl suspend` Does not appear to fix.

**Comment by igaw** [comment] 2022-01-19 16:21
No progress in this bug report for a long time. If you think it's still relevant please reopen.

**Closed by igaw** 2022-01-19 16:21 UTC
